title: Chelsea McQueen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst
  <br><br>
  Skilled researcher with 8+ years of experience conducting primary and secondary data retrieval, analysis, and interpretation. Adept at using qualitative and quantitative methodologies for independent and collaborative research. Experienced in medical and healthcare settings. Passionate about using my diverse skills to tackle complex problems.
  <br><br>
  <a href="https://www.linkedin.com/in/chelseamcqueen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
